name: Generator Test
on: 
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run build --workspace cli
            npm test --workspace cli
      - uses: actions/upload-artifact@v4
        with:
          path: 
            cli/tests/1.*/**